[package]
name = "cheesecalc"
version = "0.2.0"
authors = ["Justin Rubek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
