[package]
name = "cheesecalc"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
# serde_json = "1.0.87"
# thiserror = { workspace = true }
# tokio = { workspace = true }
# tracing = { workspace = true }
